# Файл конфигурации Codecov
coverage:
  precision: 2
  round: down
  range: "50...80"
  status:
    project:
      default:
        target: 50%
    patch:
      default:
        target: 50%

# Конкретные файлы для исключения
ignore:
  - "**/*_test.go"
  - "**/test_*.go"
  - "**/*_mock.go"
  - "**/*_testdata.go"
  - "**/mock_*.go"
  - "examples/**/*"
  - "test/**/*"
  - "**/entities/access_rights/access_rights_test_*.go"
  - "**/entities/access_rights/access_rights_with_requester_test.go"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
