coverage:
  precision: 2
  round: down
  range: "50...80"
  status:
    project:
      default:
        target: 50%
    patch:
      default:
        target: 50%

ignore:
  - "**/*_test.go"
  - "**/test_*.go"
  - "**/*_mock.go"
  - "**/*_testdata.go"
  - "**/mock_*.go"
  - "examples/**/*"
  - "test/**/*"
  - "entities/access_rights/access_rights_test_special.go"
  - "entities/access_rights/access_rights_test_more.go"
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
