services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sh -c "go test -v ./... && go vet ./... && golangci-lint run ./..."
  
  lint:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: golangci-lint run ./...
  
  fmt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: go fmt ./...
  
  cyclo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sh -c "gocyclo -over 15 . || true"
